### ISSUE TITLE
to-do's from class on 10/12

### ISSUE THREAD

**Issue by ajrominger** [role-model/roleShiny#21]
- [x] remove non-neutral params (EQ, nu_m, E, Trait sigma)
- [x] remove param headers (e.g. "local community")
- [x] make sidebar wider
- [x] remove traits tab
- [x] whole number tick marks on generation slider for rank plot
- [x] make plotting themes the same between rank plot and timeseries (just use a white background for now)
- [x] remove the rendering of the about.Rmd and just ship an about.html file in the /inst/ dir, then read the html file using `system.file('about.html', package = 'roleShiny')`

**Comment by connor-french** [comment]
All done except the about file. For some reason, the shiny app won't run simulations when I just have it read the about.html file. Gotta figure this out

**Comment by connor-french** [comment]
got em all done with commit 06d9f229f58583ef1a5398a89a9eca842e8ed567.
